SELECT * FROM Customer
SELECT * FROM prod_cat_info
SELECT * FROM Transactions

--1. Which channel is most frequently used for transactions? 
SELECT TOP 1 Store_type,
ROUND(count(total_amt),2) TOTAL_SALE
FROM  Transactions
GROUP BY Store_type
ORDER BY TOTAL_SALE DESC

--2. What is the count of Male and Female customers in the database? 
SELECT Gender, COUNT(*) AS total_customers
FROM Customer
GROUP BY Gender;
	
--3. From which city do we have the maximum number of customers and how many?
SELECT  TOP 1 city_code ,
COUNT(*) TOTAL_CUST
FROM Customer
GROUP BY city_code
ORDER BY TOTAL_CUST DESC

--4. How many sub-categories are there under the Books category?
SELECT * 
FROM prod_cat_info
WHERE prod_cat = 'bOOKS'

--5. What is the maximum quantity of products ever ordered? 
SELECT prod_subcat_code ,MAX(Qty) AS SALE
FROM Transactions
GROUP BY prod_subcat_code


--6. What is the net total revenue generated in categories Electronics and Books?
SELECT ROUND(SUM(total_amt),2) AS TOTAL_REVENUE
FROM prod_cat_info P
LEFT JOIN Transactions T
ON T.prod_cat_code = P.prod_cat_code
WHERE P.prod_cat = 'BOOKS' OR
	P.prod_cat  = 'ELECTRONICS'


--7. How many customers have >10 transactions with us, excluding returns? 
SELECT COUNT(* ) TOTAL_CUST

FROM (SELECT T.cust_id,COUNT(T.cust_id) AS NO_OF_ORDER
FROM Transactions T
LEFT JOIN Customer C
ON T.cust_id = C.customer_Id
WHERE QTY > 0
GROUP BY T.cust_id) X
WHERE NO_OF_ORDER > 10


--8. What is the combined revenue earned from the “Electronics” & “Clothing” 
--categories, from “Flagship stores”? 
SELECT ROUND(SUM(total_amt),2) REVENUE 
FROM(SELECT Store_type,total_amt,T.prod_cat_code,prod_cat
FROM prod_cat_info P
LEFT JOIN Transactions T
ON T.prod_cat_code = P.prod_cat_code
WHERE Store_type = 'Flagship store' AND total_amt > 0) X
WHERE prod_cat = 'Electronics' OR prod_cat = 'CLOTHING'

--9. What is the total revenue generated from “Male” customers in “Electronics” 
--category? Output should display total revenue by prod sub-cat.
SELECT
	P.prod_subcat ,
	ROUND(SUM(total_amt),2) AS REVENUE
FROM Transactions T
LEFT JOIN Customer C
	ON T.cust_id = C.customer_Id
LEFT JOIN prod_cat_info P 
	ON P.prod_cat_code =T.prod_cat_code 
	and t.prod_subcat_code = p.prod_sub_cat_code
WHERE C.Gender = 'M' AND
P.prod_cat = 'ELECTRONICS'
GROUP BY P.prod_subcat;

--10.What is percentage of sales and returns by product sub category; display only top 
--5 sub categories in terms of sales? 
 -- Total sales and returns

SELECT TOP 5
    P.prod_subcat,

    SUM(CASE WHEN T.qty > 0 THEN CAST(T.total_amt AS FLOAT) END) * 100 /
    (SELECT SUM(CAST(total_amt AS FLOAT)) FROM Transactions WHERE qty > 0) 
    AS SALE_IN_PER,

    SUM(CASE WHEN T.qty < 0 THEN CAST(T.total_amt AS FLOAT) END) * 100 /
    (SELECT SUM(CAST(total_amt AS FLOAT)) FROM Transactions WHERE qty < 0) 
    AS RETURN_IN_PER

FROM prod_cat_info P
JOIN Transactions T
    ON P.prod_cat_code = T.prod_cat_code
    AND P.prod_sub_cat_code = T.prod_subcat_code

GROUP BY P.prod_subcat
ORDER BY SALE_IN_PER DESC;


--11. For all customers aged between 25 to 35 years find what is the net total revenue 
--generated by these consumers in last 30 days of transactions from max transaction 
--date available in the data?
;WITH max_date AS (
    SELECT MAX(CONVERT(DATE, tran_date,105)) AS MAXX
    FROM Transactions
)

SELECT 
    ROUND(SUM(T.total_amt),2) AS Net_Revenue
FROM Customer C
JOIN Transactions T
    ON C.customer_Id = T.cust_id
CROSS JOIN max_date M
WHERE T.Qty > 0
AND DATEDIFF(YEAR, C.DOB, M.MAXX) BETWEEN 25 AND 35
AND CONVERT(DATE, T.tran_date,105) 
    BETWEEN DATEADD(DAY,-30,M.MAXX) AND M.MAXX;



--12.Which product category has seen the max value of returns in the last 3 months of 
--transactions?


;WITH max_date AS (
    SELECT MAX(CONVERT(DATE, tran_date,105)) AS MAXX
    FROM Transactions
)
SELECT TOP 1 P.prod_cat,P.prod_cat_code,
ABS(SUM(Qty)) AS TOTAL_RETURN
FROM Transactions T
JOIN prod_cat_info P
ON T.prod_cat_code = P.prod_cat_code AND
T.prod_subcat_code = P.prod_sub_cat_code
CROSS JOIN max_date M
WHERE QTY < 0  
AND
CONVERT(DATE,T.tran_date,105) 
    BETWEEN DATEADD(MONTH,-3,M.MAXX) AND M.MAXX
 GROUP BY P.prod_cat,P.prod_cat_code
ORDER BY TOTAL_RETURN DESC

--13.Which store-type sells the maximum products; by value of sales amount and by 
--quantity sold? 
SELECT  TOP 1
Store_type,
SUM(QTY) AS QTY_SOLD,
ROUND(SUM(total_amt),2) AS SALES
FROM Transactions  
WHERE QTY >0
GROUP BY Store_type
ORDER BY QTY_SOLD DESC , SALES DESC;

--14.What are the categories for which average revenue is above the overall average
WITH OVERALL_AVG AS (
        SELECT ROUND(AVG(total_amt),2) ALLOVER_AV 
        FROM Transactions
        WHERE QTY > 0
 )
SELECT * 
FROM 
    (SELECT PROD_CAT_CODE,
    ROUND(AVG(TOTAL_AMT),2) AS AVGG
    FROM  Transactions
    WHERE Qty>0
    GROUP BY PROD_CAT_CODE) X
WHERE AVGG > (SELECT ALLOVER_AV FROM OVERALL_AVG)
;
--15. Find the average and total revenue by each subcategory for the categories which 
--are among top 5 categories in terms of quantity sold.
WITH TOP5_QTY AS (
            SELECT  TOP 5 prod_cat_code,SUM(Qty)  AS QTY_SOLD
            FROM Transactions
            WHERE QTY > 0
            GROUP BY prod_cat_code
            ORDER BY QTY_SOLD DESC
)
SELECT P.prod_cat,
P.prod_cat_code,
P.prod_subcat,
ROUND(SUM(total_amt),2) AS SALE,
ROUND(AVG(total_amt),2) AS AVERAGE
FROM Transactions T
JOIN prod_cat_info P 
ON T.prod_cat_code = P.prod_cat_code
AND T.prod_subcat_code = P.prod_sub_cat_code
WHERE QTY >0 AND
p.prod_cat_code IN  (SELECT prod_cat_code FROM TOP5_QTY)
GROUP BY P.prod_cat,P.prod_subcat,P.prod_cat_code
ORDER BY P.prod_cat
;

